### ISSUE TITLE
WorkflowManagerInstall ClientOnly tries to apply CU5 which fails

### ISSUE THREAD

**Issue by rpinxten** [microsoft/WorkflowManagerDSC#3]
When executing the WorkflowManagerInstall resource with ComponentsToInstall = 'ClientOnly', the resource first installs 'Workflow Manager Client incl CU4' and after that attempts to install 
'Workflow Manager CU5'. The latter fails with message 'The Workflow Manager CU5 installation failed. Exit code '-1' was returned.'. Running the WorkflowManager-KB4055730-x64-ENU.exe manually fails with 'Workflow Manager not found or this package does not contain compatible update'. This leads me to believe CU5 is not applicable to Workflow Manager Client installs.

**Comment by ykuijs** [comment]
I did some checking and as it turns out that CU5 indeed isn't applicable for the Workflow Manager Client. Updating the code so it won't try to install CU5 anymore when using ClientOnly.

Will be included in the next version.
