### ISSUE TITLE
Installing on server when Windows Firewall is disabled fails

### ISSUE THREAD

**Issue by IlleNilsson** [microsoft/WorkflowManagerDSC#4]
When DSC executes Add-SBHost and passes parameter EnableFirewallRules as $false, Service Fabric still tries to create firewall rules, which it can't when the firewall is turned off.

**Comment by IlleNilsson** [comment]
Workaround, turn on Windows Firewall service and disable profiles Domain, Private and Public in Windows Firewall.

**Comment by ykuijs** [comment]
I am adding a check so that when EnableFirewallRules = False, it won't use the EnableFirewallRules parameter in Add-SBHost.

Will be included in the next version.

**Comment by IlleNilsson** [comment]
Nice, thanks
